### ISSUE TITLE
Random hanging after creating account

### ISSUE THREAD

**Issue by mzenzie** [UMass-Bookshare/UMass-Bookshare#35]
After filling out the info for creating the account "flerps" (password flerps), and pressing the create button, the page hung indefinitely, and chrome eventually gave me the "no data received" error page. When I tried to log in with this account, the same thing happened. This response was different from both logging in with a non-existent account and logging in with an existing acccount (we used test, password "test"), both of which worked properly.

This was done on the most recent version of chrome.

**Comment by WDoan** [comment]
No longer an issue
