### ISSUE TITLE
navbar inconsistency

### ISSUE THREAD

**Issue by pschau** [UMass-Bookshare/UMass-Bookshare#58]
Pages are hard coded with certain navbars so if you are logged in yet go to home page, it would look like you're logged out when you are not. If you go to login screen, you can go around by going to search nav tab and going to your wishlist if your session is still active.

**Comment by btamaska** [comment]
Fixed by making the logged in nav bar different from the logged out nav bar. when a user is logged out, they can only see login and create account in the nabber
